import os
import time
from inputs import non_comp_problems
from inputs_1 import hard_problems
import ex3 as ex3

PROBLEMS = hard_problems

def generate_solved_html(problem_input, solved_board, output_file="solved_board.html"):
    """
    Generates an HTML file visualizing the SOLVED Sudoku board.
    
    Args:
        problem_input: Tuple ( (K,L), assignments, sum_constraints ) containing structural info.
        solved_board: List of Lists (NxN matrix) containing the solution integers.
        output_file: The name of the HTML file to write.
    """
    (K, L), _, sum_constraints = problem_input
    N = K * L
    
    # --- 1. Define Colors for Regions ---
    # We cycle through a palette to color the KxL regions.
    palette = [
        "#4FC3F7", "#E0E0E0", "#CE93D8", "#FFB74D", # Cyan, Grey, Purple, Orange
        "#DCE775", "#A1887F", "#81C784", "#64B5F6", # Lime, Brown, Green, Blue
        "#FF8A65", "#BA68C8", "#90A4AE", "#F06292",  # Coral, Orchid, BlueGrey, Pink
        "#AED581", "#7986CB", "#E57373", "#4DB6AC"   # LightGreen, Indigo, Red, Teal
    ]
    
    col_blocks = N // L

    def get_color(r, c):
        block_r = r // K
        block_c = c // L
        region_idx = block_r * col_blocks + block_c
        return palette[region_idx % len(palette)]

    # --- 2. Build HTML/CSS ---
    cell_size = 60 # pixels
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; padding: 20px; background: #f4f4f4; }}
            h1 {{ text-align: center; color: #333; margin-bottom: 10px; }}
            .status {{ text-align: center; color: #2E7D32; font-weight: bold; margin-bottom: 20px; }}
            .board-container {{
                position: relative;
                width: {N * cell_size}px;
                height: {N * cell_size}px;
                margin: 0 auto;
                border: 4px solid #333;
                background: white;
                box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            }}
            .grid-table {{
                width: 100%;
                height: 100%;
                border-collapse: collapse;
                table-layout: fixed;
            }}
            td {{
                width: {cell_size}px;
                height: {cell_size}px;
                text-align: center;
                vertical-align: middle;
                font-size: 24px;
                font-weight: bold;
                border: 1px solid rgba(0,0,0,0.2);
                color: #333;
                padding: 0;
            }}
            /* Sum Constraint Capsules */
            .cage {{
                position: absolute;
                border: 2px solid #D32F2F; 
                background-color: rgba(255, 255, 255, 0.8);
                border-radius: 15px;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 14px;
                color: #D32F2F;
                font-weight: bold;
                pointer-events: none; 
                z-index: 10;
                box-shadow: 1px 1px 4px rgba(0,0,0,0.2);
            }}
        </style>
    </head>
    <body>
        <h1>Sudoku Solved! ({K}x{L} Regions)</h1>
        <div class="status">Solution found by SAT Solver</div>
        <div class="board-container">
            <table class="grid-table">
    """
    
    # Generate Grid Rows using the SOLVED BOARD matrix
    for r in range(N):
        html += "<tr>"
        for c in range(N):
            bg_color = get_color(r, c)
            val = solved_board[r][c] # Grab value from solution matrix
            html += f'<td style="background-color: {bg_color};">{val}</td>'
        html += "</tr>"
    
    html += """
            </table>
    """

    # --- 3. Generate Sum Constraint Overlays ---
    for r1, c1, r2, c2, target_sum in sum_constraints:
        min_r, max_r = min(r1, r2), max(r1, r2)
        min_c, max_c = min(c1, c2), max(c1, c2)
        
        top_px = min_r * cell_size
        left_px = min_c * cell_size
        
        margin = 10
        if r1 == r2: # Horizontal
            width = (2 * cell_size) - (2 * margin)
            height = cell_size - (2 * margin)
            top_px += margin
            left_px += margin
        else: # Vertical
            width = cell_size - (2 * margin)
            height = (2 * cell_size) - (2 * margin)
            top_px += margin
            left_px += margin

        html += f"""
            <div class="cage" style="top: {top_px}px; left: {left_px}px; width: {width}px; height: {height}px;">
                <span>{target_sum}</span>
            </div>
        """

    html += """
        </div>
        <p style="text-align:center; margin-top: 20px; color: #666;">Generated by SAT Sudoku Master</p>
    </body>
    </html>
    """

    with open(output_file, "w", encoding='utf-8') as f:
        f.write(html)
    print(f" >> Visualized: {output_file}")


def solve_and_visualize():
    # Create output directory if it doesn't exist
    output_dir = "solved_boards"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    print(f"Found {len(PROBLEMS)} problems in inputs.py...")

    for i, problem in enumerate(PROBLEMS):
        print(f"\n--- Solving Problem {i + 1} ---")
        
        start_time = time.time()
        
        # 1. Translate to CNF
        print("Translating to CNF...", end=" ", flush=True)
        variables, cnf_formula = ex3.to_CNF(problem)
        print("Done.")
        
        # 2. Solve SAT
        print("Running SAT Solver...", end=" ", flush=True)
        is_satisfiable, assignment = ex3.solve_SAT(variables, cnf_formula, {})
        print(f"Done. Satisfiable? {is_satisfiable}")
        
        # 3. Generate Assignment and Visualize
        if is_satisfiable:
            # Convert boolean assignment back to N x N matrix
            solved_board = ex3.numbers_assignment(variables, assignment, problem)
            
            # Generate HTML
            filename = os.path.join(output_dir, f"solution_{i+1}.html")
            generate_solved_html(problem, solved_board, filename)
        else:
            print(f" >> No solution found for Problem {i+1}, skipping visualization.")
            
        elapsed = time.time() - start_time
        print(f"Time taken: {elapsed:.4f} seconds")

if __name__ == "__main__":
    solve_and_visualize()